### ISSUE TITLE
Blackfynn-python object not accessible across threads? 

### ISSUE THREAD

**Issue by Tehsurfer** [nih-sparc/data-portal#21]
Hi all!

Not sure if I am doing something wrong here but I am beginning to create some _api/map_  routes as outlined in the wiki and have had an issue I've been thinking about so thought I would open up a conversation.

Issue
======
Flask server is multi-threaded but the global bf object we wish to access is thread locked

Context
------
I've made few routes that make requests to the python client using the global python object that gets set up before the first request

Code
------
#### api/api.py
```python
global bf
    print(Config.BLACKFYNN_API_TOKEN)

    bf = Blackfynn(
        api_token=Config.BLACKFYNN_API_TOKEN,
        api_secret=Config.BLACKFYNN_API_SECRET,
        env_override=False,
        host=Config.BLACKFYNN_API_HOST,
        concepts_api_host=Config.BLACKFYNN_CONCEPTS_API_HOST
    )
```

However if we make calls to this object later on say with: 
#### map_core/api/map_core_api.py
```python
# This route returns the names of timeseries data for the current bf object
@map_api_blueprint.route('/get_timeseries_dataset_names', methods=['GET'])
def get_timeseries_dataset_names():
    global bf
    data_sets = bf.datasets()

    global time_series_items
    time_series_items = []
    time_series_names = []
    for data_set in data_sets:
        for item in data_set.items:
            if item.type is 'TimeSeries':
                time_series_items.append(item)
                time_series_names.append(item.name)

    return json.dumps({'names': time_series_names})

```

Error
------
We eventually will get an error once we try to access the `global bf` object but are on a different thread. 

```
[14/Mar/2019 02:06:17] INFO - 127.0.0.1 - - [14/Mar/2019 02:06:17] "GET /map/api/get_channels HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jessekhorasanee/workspace/data-portal/map_core/api/map_core_api.py", line 133, in channels
    data = item.get_data(length='1s')
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/blackfynn/models.py", line 1154, in get_data
    return self._api.timeseries.get_ts_data(self,start=start, end=end, length=length, channels=channels, use_cache=use_cache)
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/blackfynn/api/timeseries.py", line 440, in get_ts_data
    for tmp_df in ts_iter:
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/blackfynn/api/timeseries.py", line 425, in get_ts_data_iter
    values = [next(i, None) for i in channel_chunks]
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/blackfynn/api/timeseries.py", line 425, in <listcomp>
    values = [next(i, None) for i in channel_chunks]
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/blackfynn/api/timeseries.py", line 194, in get_chunks
    data = page.get(self.api)
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/blackfynn/api/timeseries.py", line 97, in get
    cache_exists = cache.check_page(self.channel, self.page)
  File "/home/jessekhorasanee/workspace/data-portal/venv_data/lib/python3.6/site-packages/blackfynn/cache/cache.py", line 242, in check_page
    return r is not None
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 139689929074432 and this is thread id 139689849779968.

```

## _Further details_

- OS: Windows 10 and Ubuntu 16.04 
- Python: 3.6
- blackfynn-python:  v2.8.0
- Repo: https://github.com/Tehsurfer/data-portal
- Test Site: http://35.201.199.224/map/

**Comment by jwagenaar** [comment]
Interesting. we are looking if there are maybe better patterns to get around this. You should always be able to create a new instance of the Blackfynn object in each thread as a workaround as well.

**Comment by merky** [comment]
@Tehsurfer Which version of the client are you running?

**Comment by jwagenaar** [comment]
@merky I think 2.8 (from requirements.txt)

**Comment by Tehsurfer** [comment]
Hi @merky and @jwagenaar, thanks for having a look at this. 

> I think 2.8 (from requirements.txt)
Yeah, you're correct, I have been running blackfynn-python 2.8.0,
> or at least that's what is running on prod version.
and I am getting the error when running the site on `heroku-postbuild` ( that's the prod version right? )

> create a new instance of the Blackfynn object in each thread as a workaround as well.
Thanks for the recommendation. I'll try implementing it with creating a Blackfynn object on each threads creation.

**Comment by Tehsurfer** [comment]
Just an update, I've tried creating a Blackfynn object for each thread with the following function: 

```python

import threading
t_local = threading.local()

def get_bf():
    global t_local

    if not hasattr(t_local, 'bf'):
        t_local.bf = Blackfynn(
        api_token=Config.BLACKFYNN_API_TOKEN,
        api_secret=Config.BLACKFYNN_API_SECRET,
        env_override=False,
        host=Config.BLACKFYNN_API_HOST,
        concepts_api_host=Config.BLACKFYNN_CONCEPTS_API_HOST
    )

    return t_local.bf
```

However I have a bit of a issue as a I plan on going a few calls deep on the api, specifically:

```python
# /api/get_data: Returns data relating to the first timeseries dataset
@map_api_blueprint.route('/get_data', methods=['GET'])
def get_datset():
    bf = get_bf()
    data_sets = bf.datasets()
    for data_set in data_sets:
        for item in data_set.items:
            if item.type is 'TimeSeries':
                 item.get_data(length='1s')
                 break
```

The returns the same threading error as before, which is surprising as I should have just fetched the correct Blackfynn object for the thread right?

**Comment by merky** [comment]
@Tehsurfer This seems like a fundamental limitation on SQLite and how the BF library utilizes it. 

I would advise turning off data caching (which is what SQLite is used for). If you're not retrieving timeseries values, this shouldn't affect you. To disable the data cache, ensure that the environment variable `BLACKFYNN_USE_CACHE` is set to `0` (see [developer docs](https://developer.blackfynn.io/python/latest/configuration.html#environment-variables) for more details).

**Comment by jwagenaar** [comment]
@merky thanks, yes that makes sense. I'll set the appropriate env-variable in Heroku

**Comment by nickerso** [comment]
What impact will this have with time series data? (which is currently the main type of data we are pulling out of BF...)

**Comment by Tehsurfer** [comment]
Thanks for following up on this @merky. I couldn't get the threaded requests to work by creating a cofig.ini file in _/home/.blackfynn_ in Ubuntu or Window. But you gave me the idea of using `item.get_data(length=length, use_cache=False)`. As far as I can tell this appears to work. At least work under my testing of making calls from different browsers at the same time. 

Here is my config file, let me know if you see anything that is glaringly wrong:
_config.ini_
```ini
# Global settings
[global]
default_profile = default
use_cache = True
use_cache = False
BLACKFYNN_USE_CACHE = 0

# Profiles
[default]
api_token = c09be34d-5696-4c49-b174-7fe3fb3194af
api_secret = 87092fd-b3ad-4de9-bf78-2dbcedb7737a

[debug_mode]
use_cache = false
api_token = c09be34d-5696-4c49-b174-7fe3fb3194af
api_secret = 87092fd-b3ad-4de9-bf78-2dbcedb7737a

[super_conn]
api_token = da064188-47e4-43b0-b5cd-91805b7522d7
api_secret = 2a543888-d24d-4958-8833-3311a55e4ed6

# Settings for the Blackfynn CLI Agent
[agent]
```
